name: "CI - Test Features"
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        baseImage:
          - ghcr.io/artifex1/audit-image-base:main
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Run all tests against '${{ matrix.baseImage }}'"
        run: devcontainer features test --base-image ${{ matrix.baseImage }}
